jobs:
  Job1:
    name: Job 1
    steps:
      - type: maven
        pom-location: pom.xml
        name: clean test
        goals: clean test
  Job2:
    name: Job 2
    integrations:
      - NpmRegistry: NpmRegistry_0
      - Docker: Docker_0
  Job3:
    name: Job 3
  Job4:
    name: Job 4
  Job5:
    name: Job 5
  Job6:
    name: Job 6
  Job7:
    name: Job 7
parameters:
  level: pipeline
