jobs:
  Job1:
    name: Job 1
    steps:
      - type: maven
        pom-location: pom.xml
        name: clean test
        goals: clean test
  Job2:
    name: Job 2
    steps:
      - type: maven
        pom-location: pom.xml
        name: clean test
        goals: clean test
  Job3:
    name: Job 3
  Job4:
    name: Job 4
parameters:
  level: pipeline
